//1. Using dot and bracket notation modify the existing object values to replace the information with your own

var me = {
	'name': 'Jake Overall',
	'age': 29,
	'hair color': 'brown'
};

function replaceData(string1, int1, string2) {
	me.name = string1
	me.age = int1
	me['hair color'] = string2 //I think this is what the instructions are asking for?
	return me
}

// console.log(replaceData('Cameron Sharp', 36, 'light brown'))

//2. Iterate over the object to console.log the propery or key names. 

function itAndSpit(obj) { //Wasn't sure what you were looking for at first so wrote this for a similar effect
	var keyNames = Object.getOwnPropertyNames(me)
	for (var i = 0; i < keyNames.length; i++) {
		var key = keyNames[i];
		console.log(key)

	}
}

// itAndSpit(me)

function itAndSpit2(obj){
	for (var key in me) {
		if (me.hasOwnProperty(key)) {
			console.log(key) //Almost entirely generated by VS code autofill for the for-in loop *shrug*
		}
	}
}

// itAndSpit2(me)